config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update]
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with:  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  mount_uploader :icon, IconUploader
  mount_uploader :header, HeaderUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        end
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました'
      redirect_to @user
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end  
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました'
      redirect_to @user
    else
      flash[:danger] = 'ユーザの登録に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = 'プロフィールは正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = 'プロフィールは更新されませんでした'
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon, :profile, :remove_icon, :remove_header)
  end
  
  def correct_user
    @user = User.find(params[:id])
    unless @user  = current_user
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user 
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Sous-vide.Lab</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control" type="search" placeholder="レシピ検索" aria-label="Search">
      </form>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">詳細検索</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">温度早見表</a>
        </li>
      </ul>
      <% if logged_in? %>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'マイページ', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to '新規登録', signup_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログイン', login_path, class: 'nav-link' %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SousVideLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %> 
    </div>
    <%= yield %>
  </body>
</html>

app/views/toppages/index.html.erb
<img src="beef.jpg">

app/views/users/edit.html.erb
<div class="text-left ml-5 mb-4">
  <h1>プロフィール編集</h1>
</div>

<div class="container">
  <%= form_with(model: @user,local: true)do |f| %>
      <div class="row">
        <label class="col-4">プロフィール画像</label>
        <div class="col-8">
          <%= f.file_field :icon %>
          <br>
          <p><%= f.check_box :remove_icon %>画像を削除する</p>
        </div>
      </div>
      <div class="row">
        <label class="col-4">ヘッダー画像</label>
        <div class="col-8">
          <%= f.file_field :header %>
          <br>
          <p><%= f.check_box :remove_header %>画像を削除する</p>
        </div>
      </div>
      <div class="row">
        <label class="col-4">ユーザ名</label>
        <div class="col-8"><%= f.text_field :name %></div>
      </div>
      <div class="row">
        <label class="col-4">プロフィール</label>
        <div class="col-8"><%= f.text_field :profile %></div>
      </div>
    <div class="text-center">
      <%= f.submit 'プロフィール更新', class: 'btn btn-dark' %>
    </div>
  <% end %>
</div>
  

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
    <h1>新規登録</h1>
</div>

<div class="row">
  <div class="offset-sm-3 col-sm-6 mb-3">
        
    <%= form_with(model: @user, local: true) do |f| %>
    
      <div class="form-group">
        <%= f.text_field :name, class: 'form-control', placeholder: 'ユーザ名' %>
      </div>
      
      <div class="form-group">
        <%= f.email_field :email, class: 'form-control', placeholder: 'メールアドレス' %>
      </div>
      
      <div class="form-group">
        <%= f.password_field :password, class: 'form-control', placeholder: 'パスワード' %>
      </div>
      
      <div class="form-group">
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'パスワード（確認用）' %>
      </div>
      
      <div class="text-center">
        <%= f.submit 'アカウント作成', class: 'btn btn-dark' %>
      </div>
    <% end %>
    <div class="text-center">登録済みの方は<%= link_to 'こちら', login_path %></div>
  </div>
</div>

app/views/users/show.html.erb
<p><%= image_tag @user.thumb.icon_url if @user.icon? %></p>

<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <h1>プロフィール</h1>
      <br>
      <div class ="border">
        <%= @user.profile %>
      </div>
    </div>
    <div class="col-sm-9 text-center ">
      <% if @user == current_user %>
        <button type="button" class="btn btn-secondary"><%= link_to 'プロフィール編集', edit_user_path %></button>
      <% end %>
      <button type="button" class="btn btn-secondary">お気に入り</button>    
      <button type="button" class="btn btn-secondary">マイレシピ</button>
      <button type="button" class="btn btn-secondary">レシピ投稿</button>  
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>